### ISSUE TITLE
향후 작업 항목 목록

### ISSUE THREAD

**Issue by Siltarae** [programmers-kdt-full-stack-3rd/community-board#106]
## 어떤 기능인가요?

나중에 작업할 내용 목록

### FE
- [x] 로그인시 유효성검사 따로 분리 (리팩토링)
- [x] 회원가입, 로그인 시 유효성검사 안지켰을때 style변경
- [x] 비밀번호 복사 방지 기능 추가

### BE
- [x] 비밀번호가 기존 비밀번호와 같은지 확인 작업 필요 기능 추가
- [x] 기존 유저의 userId와 tenpToken의 userId가 일치하는지 확인하는 로직 추가
- [x] users_router 에서 인증 우선순위 변경
- [x] 회원가입시 닉네임 중복 체크
- [x] BE 에서 회원가입시 비밀번호, 비밀번호 확인 일치 여부 검사

**Comment by HungKungE** [comment]
로그인 페이지에서 추가 구현할 것이라면
"마지막에 로그인한 이메일 기억하기"가 있습니다
