### ISSUE TITLE
[BE] 게시글 열람 시 조회수 증가

### ISSUE THREAD

**Issue by yejunian** [programmers-kdt-full-stack-3rd/community-board#108]
## 어떤 기능인가요?

게시글 열람 시 조회수에 1을 더하는 기능입니다.

`posts` 테이블에 `views` 컬럼이 존재하고 클라이언트에서도 조회수를 표시해 주지만, 기록해 둔 스펙에는 조회수를 증가시키는 기능이 없어서 제안합니다.

### 로직 제안

1. 게시글 내용 보기 API 요청 수신 (`GET /api/post/{post_id}`)
2. ID가 `post_id`인 게시글을 DB에서 조회 및 매핑 (여기까지 기존 구현 내용과 동일합니다.)
3. 조회 성공 시, DB에서 ID가 `post_id`인 게시글의 `views` 컬럼을 1 큰 값으로 갱신
4. 갱신 성공 시, \<2\>에서 얻은 객체의 `views` 필드에 1을 더하여 성공 응답
   - 갱신 실패 시, \<2\>에서 얻은 객체를 변경하지 않고 응답

한계: 한 게시글을 같은 사람이 여러 번 읽어도 조회수가 매번 증가합니다.

## 작업 상세 내용

- [ ] ID가 `post_id`인 게시글 조회 성공 시, DB에서 ID가 `post_id`인 게시글의 `views` 컬럼을 1 큰 값으로 갱신
- [ ] 조회수 갱신 성공 시, 게시글 조회 결과로 얻은 객체의 `views` 필드에 1을 더하여 응답
- [ ] 조회수 갱신 실패 시, 게시글 조회 결과로 얻은 객체를 변경하지 않고 응답

## 기타

- 더 나은 구현 방법이나 다른 의견 있으면 말씀해 주세요.

**Comment by HungKungE** [comment]
추가로 user_id가 있는 경우에
user_id === author_id 이면 조회수는 증가시키지 않도록 하려는데 괜찮을까요?

**Comment by HungKungE** [comment]
조회수는 원래 같은사람이 여러번 보면 여러번 증가하는 걸로 알고 있어서 괜찮을 것 같습니다.
