### ISSUE TITLE
[FE] client login 상태 관리

### ISSUE THREAD

**Issue by HungKungE** [programmers-kdt-full-stack-3rd/community-board#109]
### 문제 상황
- 다음 상황에서 로그아웃 기능을 수행할 수 없음
    - 로그인 이후 로그아웃을 하지 않음
    - 토큰 만료 이후 사이트 접속 (토큰이 만료되어 로그아웃이 동작 x)

### 해결책
- client 자체적인 login state 관리
    - 로그인 성공 시, zustand를 통해 관리하는 로그인 state를 받음 (loginTime, nickname, isLogin)
    - 이 때, refresh token이 만료 기한이 1일이므로 현재시각 > loginTime + 1 day 일 경우
       로컬 스토리지에 저장된 login state를 삭제하는 기능이 필요

## 작업 상세 내용

- [ ] "현재 시각" > "loginTime + 1일" 일 때 로컬 스토리지 데이터 삭제

**Comment by Siltarae** [comment]
이 문제에 대해 고민하고 있었습니다. 서버와 클라이언트 간의 로그인 상태 동기화가 핵심 문제라고 판단했습니다.

제가 생각한 방법은 페이지 로드마다 쿠키 존재 여부를 확인하는 것이었습니다. 이를 통해 기본적인 동기화는 가능할 것 같습니다.

하지만 여기서 한 가지 걱정되는 점이 있습니다. 
쿠키는 존재하지만 모종의 이유로 로컬 스토리지의 정보만 삭제된 경우입니다. 이때 쿠키도 같이 삭제할것인지 서버측에서 다시 유저 정보를 받아올 것인지가 고민이 있었습니다.

이 문제를 해결하기 위한 더 효과적인 방법이나 추가적인 고려사항이 있을까요?

**Comment by HungKungE** [comment]
제 주관적인 생각을 말씀드리면
로컬 스토리지를 기준으로 로그인 상태를 동기화 시키는게 더 좋다고 생각합니다.
로컬 스토리지의 loginTime으로도 충분히 토큰 만료 여부를 판단 가능하므로
불필요한 서버 요청을 줄일 수 있고 구현이 간단합니다.

반면에 쿠키 기준으로 로그인 상태를 동기화 하면
토큰 유효성 판단을 위해서 반드시 서버에 요청을 보내야 하기 때문에
첫번째 방식보다 비효율적이라고 생각합니다.

## 로컬 스토리지 기준
- 로컬 스토리지 값 존재 여부 or isLogin -> 로그인 여부 판단 가능
- 로컬 스토리지의 loginTime -> 토큰 만료 판단 가능
- 위의 모든 것을 서버에 요청을 보내지 않고도 처리할 수 있음

## 쿠키 기준
- 쿠키가 존재
    - 로컬 스토리지 x -> 로그인 판단을 위해 서버로 token 검증 요청 -> 로그인 상태 응답
    - 로컬 스토리지 o -> 다른 api 요청 시, 서버에서 token 검증
- 로컬 스토리지 값이 있으나 없으나 항상 token을 검증해야 함
- 로컬 기준이면 로컬 스토리지 x 일 경우의 task가 사라짐

**Comment by Siltarae** [comment]
일반적인 사용 시나리오에서는 상관이 없을것 같습니다. 하지만 토큰이 변조 됐을때도 쿠키가 삭제가 되기 때문에 로컬스토리지 를 기준으로 판단한다면 클라이언트와 서버간의 로그인 여부가 불일치가 일어날거같습니다.

**Comment by HungKungE** [comment]
토큰 변조같은 특수한 상황이 발생했을 때는
아래와 같이 처리하면 된다고 생각합니다.
이 때, 추가할 내용은 하나밖에 없습니다.

- 로컬 스토리지 값이 정상이므로 api 요청을 보낼 수 있음
- api 요청을 보내면, 서버에서 토큰 검증
- 변조된 토큰 확인 + 쿠키 삭제 및 에러 반환
- 에러가 반환되면 로컬 스토리지 값 삭제 (강제 로그아웃 처리) -> 이 부분만 추가하면 됨

**Comment by HungKungE** [comment]
음 다시 보니 제가 너무 제 생각만 주장한것 같네요.

만약, 말씀해주신 대로 페이지 로드마다 쿠키 존재 여부를 확인하는 방식으로 만드신다면
쿠키는 존재하지만 모종의 이유로 로컬 스토리지의 정보만 삭제된 경우에는
쿠키도 삭제하는 것이 더 좋다고 생각합니다.

**Comment by Siltarae** [comment]
> 토큰 변조같은 특수한 상황이 발생했을 때는 아래와 같이 처리하면 된다고 생각합니다. 이 때, 추가할 내용은 하나밖에 없습니다.
> 
> * 로컬 스토리지 값이 정상이므로 api 요청을 보낼 수 있음
> * api 요청을 보내면, 서버에서 토큰 검증
> * 변조된 토큰 확인 + 쿠키 삭제 및 에러 반환
> * 에러가 반환되면 로컬 스토리지 값 삭제 (강제 로그아웃 처리) -> 이 부분만 추가하면 됨

아닙니다. 저도 이방법을 생각은 했었지만
제가 작성하지 않은 코드 부분을 수정하는 것은 적절하지 않다고 판단하여 다른 접근 방식을 모색했습니다.
제가 생각했던방식은 
1. 토큰 인증 부분에서 오류가 떴을때 특정 에러 메시지를 반환.
2. 클라이언트의 HttpRequest 함수 에서 이 특정 에러 메시지를 감지합니다.
3. 해당 에러 메시지가 감지되면 로컬 스토리지의 관련 정보를 삭제합니다.

제가 이해한게 맞다면 비슷하게 생각하신거 맞나요?
맞다면 이 방식대로 수정하겠습니다.

**Comment by HungKungE** [comment]
네 맞습니다!
