### ISSUE TITLE
nginx세팅 시 kafka 에러

### ISSUE THREAD

**Issue by estiemoon** [programmers-kdt-full-stack-3rd/community-board#283]
## 어떤 버그인가요?

> 카프카 실행 시 에러

## 어떤 상황에서 발생한 버그인가요?

*  #236 
에서 nginx 세팅 시 카프카쪽에서 에러가 발생합니다.
더 필요한 에러 코드 필요하시면 댓글 달아주세요.

## 참고할만한 자료(선택)
<img width="1319" alt="스크린샷 2024-10-04 오후 4 23 32" src="https://github.com/user-attachments/assets/3558650b-9dbb-4e27-b71e-6c56b3cb7684">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 23 38" src="https://github.com/user-attachments/assets/626ad27f-fdf5-4af7-b1f5-a0f29626299c">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 23 44" src="https://github.com/user-attachments/assets/4c4cbc31-f79f-4d98-b464-96dcd63526e2">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 24 06" src="https://github.com/user-attachments/assets/bd74cf4a-1db6-4614-b0d8-27d7050a90e9">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 24 14" src="https://github.com/user-attachments/assets/667fe13a-e41b-4f33-ba27-613bb2ff252e">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 24 18" src="https://github.com/user-attachments/assets/651219ab-e9d0-4349-8fe1-3e28004336ae">
<img width="1319" alt="스크린샷 2024-10-04 오후 4 24 25" src="https://github.com/user-attachments/assets/f2a7f666-9c02-4159-9aa7-0a6761ece756">

**Comment by estiemoon** [comment]
이제 됩니다!!!
<img width="405" alt="스크린샷 2024-10-04 오후 4 56 39" src="https://github.com/user-attachments/assets/e43f88b9-c130-4322-a7f5-daee9615d284">
파일 명에 공백이 들어가서 에러가 났던 것 같은데
datas폴더를 아예지우고 새로 시작했더니 작동해요!!

**Comment by HungKungE** [comment]
다행입니다
