### ISSUE TITLE
[BE] 댓글 API URL 변경 제안

### ISSUE THREAD

**Issue by yejunian** [programmers-kdt-full-stack-3rd/community-board#55]
## 어떤 기능인가요?

일관성과 직관성을 향상하는 방향으로 댓글 API의 URL을 변경하고자 합니다.

<mark>아래 변경안에 두 분께서 모두 긍정의 의견을 남겨 주시면 변경 작업을 진행하겠습니다.</mark>

### 댓글 API URL 변경안

- **(1) 조회** → `GET /api/comment?post_id={}` ... `post_id`를 param에서 query로 옮김
- **(2) 등록** → ~~`POST /api/comment?post_id={}` ... `post_id`를 body에서 query로 옮김~~
  - → `POST /api/comment` ... 현재 구현 유지
- **(3) 수정** → ~~`PATCH /api/comment/{comment_id}` ... `comment_id`를 body에서 param으로 옮김~~
  - → `PATCH /api/comment` ... 현재 구현 유지
- **(4) 삭제** → `DELETE /api/comment/{comment_id}` ... `comment_id`를 body에서 param으로 옮김

### 상세 설명

현재는 댓글 API가 아래와 같이 구성되어 있습니다.

- **(1) 조회**: `GET /api/comment/{post_id}`
- **(2) 등록**: `POST /api/comment`
  - 토큰 → author_id
  - Request body → post_id, content
- **(3) 수정**: `PATCH /api/comment`
  - 토큰 → author_id
  - Request body → comment_id, content
- **(4) 삭제**: `DELETE /api/comment`
  - 토큰 → author_id
  - Request body → comment_id

(3), (4) 구현 중에 `comment_id`를 변경안처럼 param으로 받을지 고민했습니다. 이렇게 하면 게시글 수정·삭제 API와의 일관성을 얻을 수 있습니다. (실제 구현은 일단 request body로 받도록 했습니다.)

하지만 URL의 `comment` 아래에 `{post_id}`와 `{comment_id}`가 섞여서 댓글 API 내에서는 일관성이 떨어집니다. (1)에서 `GET /api/comment/1`이 1번 댓글 조회처럼 보이지만, 구현은 1번 게시글의 댓글 조회라서 직관성이 부족합니다. 따라서 (1), (2)도 함께 변경하면 좋겠다는 생각이 들어서 이런 제안을 드리게 되었습니다.

## 작업 상세 내용

- 댓글 API 변경 논의
  - [x] 댓글 API 변경안 작성
  - [x] 댓글 API 변경 여부 및 변경안 확정
- 협의 내용 반영
  - [x] Wiki 문서 업데이트
  - [x] 댓글 API 변경 작업 진행
  - [x] 변경사항 PR 및 코드 리뷰

**Comment by Siltarae** [comment]
저는 변경안이 더 직관적으로 보이네요 찬성입니다 👍

**Comment by HungKungE** [comment]
1. GET의 경우에는 말씀해주신 것처럼 comment/1 같은 URL이 1번 게시글에 쓰는 것인지 1번 댓글을 생성하는 것인지 모호할 수 있다고 생각해서
param보다는 query string이 더 좋아보입니다.

2. POST 요청은 댓글 생성에 필요한 정보들을 BODY에 담아 전달하고 기능들도 모두 body의 데이터를 사용하는 방향으로 개발되어 있으므로
query로 바꾸기 보다는 기존의 방식을 유지하는 것이 좋아 보입니다.

3. PUT, PATCH 또한 정보 수정에 필요한 정보들을 Body에 담고, 이를 기준으로 개발되었기 때문에
기존의 body 방식을 유지하는 것이 좋아보입니다.

4. DELETE의 경우에는 Body에 정보를 담기 보다는 query string이나 param을 사용하는 것이 명확하고 좋아 보입니다.

**Comment by yejunian** [comment]
@Siltarae @HungKungE
피드백 감사드립니다. 의견 주신 대로 수정하면 POST, PUT, PATCH 요청의 형태가 일관성 있게 보이겠네요!

아래와 같이 GET, DELETE만 수정 진행하겠습니다.

- **(1) 조회** → `GET /api/comment?post_id={}` ... `post_id`를 param에서 query로 옮김
- ~~**(2) 등록** → `POST /api/comment` ... 현재 구현 유지~~
- ~~**(3) 수정** → `PATCH /api/comment` ... 현재 구현 유지~~
- **(4) 삭제** → `DELETE /api/comment/{comment_id}` ... `comment_id`를 body에서 param으로 옮김
