### ISSUE TITLE
[BUG] HTTP 오류가 try-catch의 catch 블록에서 처리되지 않는 문제

### ISSUE THREAD

**Issue by Siltarae** [programmers-kdt-full-stack-3rd/community-board#73]
## 어떤 버그인가요?

HTTP 오류(ex: 상태코드 400, 500)가 try-catch문에 catch 블록에서 잡히지 않고 있습니다.

## 어떤 상황에서 발생한 버그인가요?

- Given : 사용자가 로그인을 시도합니다.
- When: 로그인시 정보를 잘못 입력하여 서버에서 400 Bad Request를 반환 합니다.
- Then: 에러가 catch 블록에서 처리되지 않고 try 블록 내에서 정상적으로 처리됩니다.

```ts
  const handleLoginButton = async () => {
    const body = {
      email,
      password,
    };

    try {
      const result = await sendPostLoginRequest(body);
      console.log("try문: ", result);
    } catch (err) {
      console.error("catch문: ", err);
    }
  };
  ```
![image](https://github.com/user-attachments/assets/e4214970-a00e-436c-8efc-fe3698c7a12c)

## 예상 결과
HTTP 오류 (ex: 상태코드 400, 500)가 catch 블록에서 잡혀 처리되어야 합니다.

**Comment by HungKungE** [comment]
http request함수에는 에러처리하는 부분이 없습니다.

**Comment by HungKungE** [comment]
서버에 만든 api들이 실패했을 때,
똑같은 status를 반환 받더라도
각자 실패 사유에 대한 텍스트가 다르기때문에
일괄적으로 이를 핸들링하도록 만드는게 어렵다고 판단해서 그렇습니다.

**Comment by HungKungE** [comment]
따라서 저렇게 try catch는 방법보다는
해당 sendRequest 함수를 사용하는 곳에서
then키워드를 활용하여 res.status가 에러 코드일 경우 에러 알림하는 방식을 사용하는것을 추천합니다.

**Comment by HungKungE** [comment]
예시
```ts
// Posts.tsx
  const getPosts = () => {
    const query = `?index=1&perPage=5&sortBy=`+SortBy.LIKES;

    sendGetPostsRequest(query).then((res)=>{
      if(res.status!==200){
          alert("일시적 오류 발생!");
          return;
      }
      console.log(res);
    });
  };
```

**Comment by HungKungE** [comment]
만약 try catch를 사용하실 거면

sendRequest에서 직접 status >= 400 인지를 비교하고
에러 메세지를 출력하게 하면 될 듯 합니다.

```ts
const sendRequest = async () => {
    const res = await httpRequest(~~);
    
    if(res.status >= 400){
        // 에러 메세지 보여주기
        return;
    }
    return res;
};
```

**Comment by Siltarae** [comment]
```ts
// 기존 httpRequest 함수
  if (!response.ok) {
    throw {
      ...responseJson,
      status: response.status,
    };
  }

  return {
    ...responseJson,
    status: response.status,
  };
```
이런식의 처리는 별로일까요? 에러처리를 그래도 then에서 처리하는거보다 catch에서 처리하는게 나은거같아서요.

**Comment by HungKungE** [comment]
이것도 취향차이 같네요.
저는 server에서 사용자의 요청에 대해 이미 충분한 에러 핸들링을 한다고 생각해서
client에서는 try catch 사용하지 않고 then 키워드 안에서 if else로만 다루는 걸 선호합니다.

이 부분에 대해서는 합의가 필요해 보입니다.

**Comment by HungKungE** [comment]
혹시 이 부분에 대해서는
UI 먼저 구현하고 나중에 정해도 될까요?

**Comment by Siltarae** [comment]
네 알겠습니다.
